import Header from "@/components/Common/Header";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import KProvider from "@/components/KProvider";
import SEO from "./../../next-seo.config";
import { DefaultSeo, SocialProfileJsonLd } from "next-seo";
import CustomToaster from "@/components/Common/CustomToaster";
import Circles from "@/components/Common/Circles";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="relative min-h-screen overflow-x-hidden">
          <Header />
          <KProvider>
            <NextTopLoader
              color="#A0A0A0"
              initialPosition={0.3}
              crawlSpeed={200}
              height={3}
              crawl={false}
              showSpinner={false}
              easing="ease"
              speed={200}
            />
            <DefaultSeo {...SEO} />
            <SocialProfileJsonLd
              type="Person"
              name="Bjorn-Donald"
              url="https://6lackbjorn.com/"
              sameAs={["https://twitter.com/6lackbjorn"]}
            />
          </KProvider>

          {/* <NextNProgress
            color="#A0A0A0"
            startPosition={0.3}
            stopDelayMs={200}
            height={3}
            options={{ showSpinner: false }}
          /> */}
          <div id="main">
            {children}
            <CustomToaster />
            <Circles />
          </div>
        </div>
      </body>
    </html>
  );
}
