#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "💻 Running pre-commit hook..."

bun format || 
(
    echo "🚨 Format failed.";
    false;
)

bun lint || 
(
    echo "🚨 Lint failed.";
    false;
)

bun types:check || 
(
    echo "🚨 Type check failed.";
    false;
)

echo "✅ All checks passed 
        Committing"